### ISSUE TITLE
design for desktop navigation sub-menu

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#1]
I'm not sure if we discussed a solution to this, but I think we need a sub-menu, on click or hover, for the portfolio section. Wasn't sure how to design it, so I just applied a quick style similar to the mobile design. Any design suggestions? 
#### Screenshot

<img width="247" alt="screen shot 2016-04-16 at 1 59 24 pm" src="https://cloud.githubusercontent.com/assets/1847581/14583385/777bc1e4-03ee-11e6-9fda-92bbd5ffa55c.png">

**Comment by chrissim15** [comment]
I was thinking the same thing - sub-menu on hover. What about something like this? 

![screen shot 2016-04-25 at 1 37 29 am](https://cloud.githubusercontent.com/assets/18566485/14808209/795feb06-0b51-11e6-8643-3ef0446d24be.png)

Similar, but a bit more integrated with the background color same as the nav menu? I was also thinking it would be cool if the menu animated down slightly - like if it expanded down and the project names / links expanded down with it (if that makes sense). Here’s a cool menu expand that I found recently for inspiration…(http://cuberto.com) Curious about your thoughts!

**Comment by davelandry** [comment]
Love it. I'll see what I can do.
