### ISSUE TITLE
front-end designer job posting

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#14]
# Front-End Developer/Designer

Datawheel, LLC is a Cambridge based startup focused on creating custom tools to analyze and visualize big data. We are a tight-knit family with a background in academia, design, and computer science.

Having just launched Data USA (datausa.io), the most comprehensive visualization of U.S. public data, we are ready to expand our team. We are looking for someone with a keen eye for design and usability to help bring our current and future products from mockup to implementation.

Personal Qualities
- Self-starter, able to work independently
- Familiar with working on a small fast-paced team
- Willingness to learn and develop new technologies

Requirements
- 3+ years experience with front-end web languages  (e.g. HTML, CSS, Javascript)
- Familiarity with Node.js environments
- Experience with rapid prototyping
- Experience in product design is a huge plus

Benefits
- Laid back work atmosphere
- Potential for international travel

**Comment by davelandry** [comment]
I just grabbed an old job posting we made a long time ago and updated/tweaked it. I'll update this as comments come in.

**Comment by melteng** [comment]
can you add "experience with rapid prototyping" and _huge_ to "plus for experience in UX and visual design"?

Also being picky I'd change "ux and visual design" to just "product design"

**Comment by davelandry** [comment]
Posted on http://www.datawheel.us/team/
