### ISSUE TITLE
Add portfolio pages for latest client work

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/datawheel#17]
- [x] Codelife
- [x] CNY Vitals
- [x] Verizon DBIR

**Comment by perpetualgrimace** [comment]
@davelandry @cesifoti @jspeis @alexandersimoes 

Took a first stab at these three portfolio pages. Let me know if you'd like to make any changes before I do a push.

![home-thumbnails 2x](https://user-images.githubusercontent.com/6193798/41489699-e90f521e-70be-11e8-8f36-c135c07a57d4.png)
![verizon-dbir 2x](https://user-images.githubusercontent.com/6193798/41489700-e920001e-70be-11e8-9987-f35eb53681a0.png)
![codelife 2x](https://user-images.githubusercontent.com/6193798/41489701-e92dad5e-70be-11e8-9954-00db1e408f43.png)
![cny-vitals 2x](https://user-images.githubusercontent.com/6193798/41489702-e93c4f44-70be-11e8-907f-9b9982086530.png)

**Comment by perpetualgrimace** [comment]
Note: the parallax backgrounds (right above the footer) weren't captured for some reason, but those are in place as well.

**Comment by davelandry** [comment]
@perpetualgrimace looking good! my only comment would be if we could get more of the cool island artwork apparent on the Codelife page. The 2nd and 3rd images seem a little redundant to me.

**Comment by davelandry** [comment]
also, just noticed the CNY footer. can we do a less literal icon for the CNY footer? doesn't even really need to match the project 100%

**Comment by perpetualgrimace** [comment]
@davelandry 

About Codelife: Sure. The gifs are showing different functionality, but I agree that it's somewhat similar in that it's based around the codeblock and project editors. What kind of description would you write to tie into the island artwork? Which view would you show?

About CNY: I'm 100% open to suggestions for different icons here.

**Comment by davelandry** [comment]
CodeLife: move the first GIF down to the second blurb of text, and make the first GIF show entering an island/slide all the way from the full-screen map page.

CNY: laptop with magnifying glass (sketch file is in Drive -> Resources -> Icons & Colors -> Website Icons -> icons.sketch)

<img width="110" alt="screen shot 2018-06-18 at 11 28 27 am" src="https://user-images.githubusercontent.com/1847581/41546123-d1553e8a-72ea-11e8-87b5-9555f93ab4e1.png">

**Comment by perpetualgrimace** [comment]
How about this for CNY instead? 

<img width="1000" alt="screen shot 2018-06-18 at 12 47 35 pm" src="https://user-images.githubusercontent.com/6193798/41550120-d23b1102-72f5-11e8-83f6-1b997bd8e670.png">

**Comment by perpetualgrimace** [comment]
Updated first gif. 
![codelife](https://user-images.githubusercontent.com/6193798/41554277-5e71df28-7302-11e8-81e6-8fe96a3fc146.gif)

**Comment by davelandry** [comment]
YES and YES

**Comment by perpetualgrimace** [comment]
f8e3d507, 852d1570, 95b516a5, fa571463, 12ab689a
