### ISSUE TITLE
Add Datawheelers new and old to team page

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/datawheel#18]
## Andrea
- [x] Take Márcio's photos
- [x] Edit Márcio's photos
- [x] Add Márcio's bio

**Comment by davelandry** [comment]
@perpetualgrimace thanks for organizing all this... I'm realizing I need to communicate with you more via github 🤖

**Comment by perpetualgrimace** [comment]
@davelandry I think you're the only one that does communicate via github 😅

**Comment by perpetualgrimace** [comment]
@davelandry we're just down to Andrea now. I have everything ready to go as soon as she gets me her bio, so feel free to have her send it my way. It'll take 2 minutes, so I don't mind.

**Comment by perpetualgrimace** [comment]
Now that I'm tagged in onboarding issues, this one feels redundant.

![giphy](https://user-images.githubusercontent.com/6193798/43407612-36dc717e-93ed-11e8-8475-8715ce6d94bb.gif)
