### ISSUE TITLE
add client list to homepage

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#19]
Very stereotypical block of client logos, [see here](http://basho.com/) for an example of what I'm talking about:

<img width="1259" alt="screen shot 2018-06-18 at 10 56 06 am" src="https://user-images.githubusercontent.com/1847581/41544270-48e816c0-72e6-11e8-9a40-62d986bbc0ea.png">

Doesn't need to scroll, could just be a tile list. 

### Full List w/ Links
I've listed the associated projects for some of these, which might help tracking down some of these logos.
- [x] [Deloitte](https://www2.deloitte.com/us/en.html) (Data USA)
- [x] [MIT](http://web.mit.edu/)
- [x] [Inter-American Development Bank](https://www.iadb.org/en)
- [x] [Estee Lauder](https://www.esteelauder.com/)
- [x] [Verizon](https://www.verizon.com/home/verizonglobalhome/ghp_landing.aspx)
- [x] [Steelcase](https://www.steelcase.com/)
- [x] [FAPEMIG](http://www.fapemig.br/) (CodeLife)
- [x] [FUNDEP](http://www.fundep.ufmg.br/) (CodeLife)
- [x] [Antofagasta Minerals](http://www.aminerals.cl/) (DataChile)
- [x] [CORFO](https://www.corfo.cl/sites/cpp/home) (DataChile)
- [x] [Entel Exlora_Lab](http://www.entel.cl/) (DataChile)
- [x] [Ministerio de Economia, Fomento y Turismo](http://www.economia.gob.cl/) (DataChile)
- [x] [DIRECON](https://www.direcon.gob.cl/) (DataChile)
- [x] [ASECH](https://home.asech.cl/) (DataChile)
- [x] [International Food and Policy Research Institute](http://www.ifpri.org/) (Data Africa)
- [x] [Central New York Community Foundation](https://cnycf.org/) (CNY Vitals)
- [x] [Wasphi](http://www.wasphi.com/) (Data KSA)
- [x] [Government of Argentina](https://www.argentina.gob.ar/)
- [x] [Authority Health](http://www.authorityhealth.org/)
- [x] [Minas Gerais Government](http://mg.gov.br/)
- [x] [FUNARBE](https://www.funarbe.org.br/en/)

**Comment by perpetualgrimace** [comment]
Should the logos link to the corresponding sites?

**Comment by davelandry** [comment]
I kept going back and forth on that idea. Part of me even thinks that (if applicable) they should link to the appropriate project page if it exists.

In the end, I leave the decision up to you.

**Comment by perpetualgrimace** [comment]
Logo grid is go. Logos are unlinked for now, but we can always add that functionality in the future if we decide to.

<img width="1150" alt="logo-grid 2x" src="https://user-images.githubusercontent.com/6193798/41616236-7e29fed0-73cb-11e8-9935-3baa1d9a39b0.png">

**Comment by davelandry** [comment]
🙏 perfect, push it!

**Comment by perpetualgrimace** [comment]
🚀 39c0dcc8
