### ISSUE TITLE
clean up animated GIFs for product pages

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#2]
- [x] the right side of the browser is cropped<br />(most visible on the Data USA profiles, cropping "Back to Top" and the search icon)
  ![crop](https://cloud.githubusercontent.com/assets/1847581/14838178/b0f8caf6-0bec-11e6-8ffb-d4fb4c974883.jpg)
- [x] scrollbars should be turned off (System Preferences > General)
  ![scroll](https://cloud.githubusercontent.com/assets/1847581/14838186/ba82cdb0-0bec-11e6-8e0f-830ffe654da2.jpg)

We also need to compress the quality/filesize. Photoshop has pretty good save for web optimizations for GIFs that I can play with. Who made the first batch of GIFs? I can handle compression if someone can spend the (tedious) time recreating these.

**Comment by chrissim15** [comment]
Jarvis was on GIF duty for the first batch. I’m not sure if I’m seeing what you mean by the right side of the browser being cropped / the visible scrollbars. 

Do they all need to be recreated? And if so, are you guys cool with the particular actions / screenshots that we got the first go-round?

**Comment by davelandry** [comment]
Sorry, I should have posted screenshots. I've updated the main post with examples.

Don't worry about recreating them right now, after we spend the time writing the text for all the pages, we'll come back to you with a final list of animated GIFs. If you don't have the time, I'm sure we can figure out how to make them ourselves.

**Comment by austin-jarvis** [comment]
Sounds good, Dave - we'll hold off on updating the GIFs until you guys decide on a final set.

**Comment by davelandry** [comment]
Alright, we've updated the text on the project pages. All of the GIFs still fit with what we wrote, so you should be good to just recreate the current set!
