### ISSUE TITLE
mobile CSS broken on portfolio pages

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#20]
<img width="502" alt="screen shot 2018-06-20 at 11 33 59 am" src="https://user-images.githubusercontent.com/1847581/41671465-2f1f7cc4-7485-11e8-8db9-7d8cae445a4c.png">

**Comment by perpetualgrimace** [comment]
Well, why'd you break it??? 😅

**Comment by perpetualgrimace** [comment]
Fixed in 4382bb32. As soon as Valerie gets me her bio I'll push it along with the updated staff photos.

**Comment by perpetualgrimace** [comment]
Should be live with the updated team page now.
