### ISSUE TITLE
portfolio descriptions not collapsing on mobile

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#3]
#### Behavior

On mobile devices, the descriptions with the GIFs on the portfolio pages don't collapse into the plus/minus buttons seen in the mockups.
#### Possible Solution

I actually think it looks better this way, so I'm proposing we keep it like this. I can be talked out of it though. 
#### Screenshot

<img width="349" alt="screen shot 2016-04-16 at 4 35 58 pm" src="https://cloud.githubusercontent.com/assets/1847581/14583501/7bac1dec-03f1-11e6-887f-72efaf2ce1d4.png">
#### Your Environment

- Browser Name and version: Mobile Safari
- Operating System and version: iOS 9

**Comment by chrissim15** [comment]
I actually don’t have a problem with the descriptions not collapsing. I feel like the information flows better that way, uninterrupted.

**Comment by davelandry** [comment]
Less work for me then! 😏
